server:
  port: 0
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: root123
    
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: api-2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
 
 
